# Generated by Django 4.2.4 on 2024-02-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_relationship_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
